# Generated by Django 5.0.2 on 2024-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_id', models.CharField(max_length=10)),
                ('Hospital_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=50)),
                ('Helpline_number', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Hospital_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=50)),
                ('Hospital_image', models.ImageField(max_length=255, null=True, upload_to='static/recipe_img')),
            ],
        ),
        migrations.CreateModel(
            name='logindetails',
            fields=[
                ('user', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
